//判断是否已登录
if(sessionStorage.getItem("sess").length<29){
//判断是否已存账号密码
	if(localStorage.getItem("log")=="access"){
    //post账号、密码到JSON接口
    	$.post(
			"http://202.116.161.73:6391/query/Sys_UserLogin",
      		{//参数
        		strUserNumber:localStorage.getItem("number"),
        		strPassWordMd5:localStorage.getItem("psw"),
        		strCurrentDate:localStorage.getItem("date"),
      		},//回调函数
      		function(data,status){
        		alert("Session：" + data.result + "\n状态：" + status);//弹出获取到的session
				//判断登入是否成功
        		if(data.result.length>29){
        		sessionStorage.setItem("sess",data.result)};//存session
      		}
    	)
  	}else{window.location.href="login.html";}
}
//后退事件
$(document).ready(function(){
   $(".back").click(function(){window.location.href="javascript:history.go(-1);";}) 
   $(".out").click(function(){
		localStorage.clear();
		sessionStorage.clear();
		window.location.href="login.html";
	}
})
